---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[tmux::default]
      - recipe[vim::default]
      - recipe[rainbow_env::install]
      - recipe[rainbow_env::dotfiles]
    attributes:
       # tmux:
         # version: "2.6"
         # checksum: "b17cd1"
    makeuser: test_kitchen_user
