---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[vim]
      - recipe[learn_chef_httpd::default]
      - recipe[learn_chef_httpd::dotfiles]

attributes:
    makeuser: test_kitchen_user
